// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # Delete existing annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Annotation ID to update
    # + locale - Locale
    # + return - successful operation 
    resource function delete [string globalCompanyId]/annotations/[string id](string locale = "en_US") returns DeleteResponse {
        return {result: "success", message: "Annotation deleted"};
    }

    # Delete calculated metrics by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The calculated metric ID to be deleted
    # + locale - Locale
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:InternalServerError (External API error; Calculated metric delete failed)
    resource function delete [string globalCompanyId]/calculatedmetrics/[string id](string locale = "en_US") returns DeleteResponse|CalculatedMetricErrorStatusInternalServerError {
        return {result: "success", message: "Calculated metric deleted"};
    }

    # Delete a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The segment ID to be deleted
    # + locale - Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:InternalServerError (External API error; Segment delete failed)
    resource function delete [string globalCompanyId]/segments/[string id](string locale = "en_US") returns string|http:InternalServerError {
        return "Segment deleted";
    }

    # Retrieve all annotations.
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + expansion - Comma-delimited list of additional annotation metadata fields to include on response
    # + includeType - Include additional annotations not owned by user. The "all" option takes precedence over "shared"
    # + locale - Locale
    # + filterByModifiedAfter - Filter list to only include annotations modified since this date (ISO8601 format)
    # + filterByDateRange - Filter list to only include annotations in the specified date range with format yyyy-MM-dd'T'HH:mm:ss/yyyy-MM-dd'T'hh:MM:ss
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + sortDirection - Sort direction (ASC or DESC
    # + sortProperty - Property to sort by (name, modified_date, id is currently allowed)
    # + return - successful operation 
    resource function get [string globalCompanyId]/annotations(("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[]? expansion, ("all"|"shared")[]? includeType, string? filterByIds, string? filterByModifiedAfter, string? filterByDateRange, int? sortDirection, string locale = "en_US", int 'limit = 10, int page = 0, string sortProperty = "id") returns ResponsePageAnalyticsAnnotation {
        return {content: [{id: "a1b2c3", name: "Spring Campaign Launch", description: "Marketing campaign kicked off across all channels", rsid: "examplersid", color: "STANDARD3", dateRange: "2026-03-01T00:00:00/2026-03-31T23:59:59", applyToAllReports: false, approved: true, favorite: false, companyId: 12345, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, createdDate: "2026-02-20T10:15:00Z", modifiedDate: "2026-02-21T08:30:00Z", reportSuiteName: "Example Site"}], totalElements: 1, numberOfElements: 1, totalPages: 1, size: 10, number: 0, firstPage: true, lastPage: true};
    }

    # Get existing annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + expansion - Comma-delimited list of additional annotation metadata fields to include on response
    # + id - Annotation ID to retrieve
    # + locale - Locale
    # + return - successful operation 
    resource function get [string globalCompanyId]/annotations/[string id](("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[]? expansion, string locale = "en_US") returns AnalyticsAnnotation {
        return {id: "a1b2c3", name: "Spring Campaign Launch", description: "Marketing campaign kicked off across all channels", rsid: "examplersid", color: "STANDARD3", dateRange: "2026-03-01T00:00:00/2026-03-31T23:59:59", applyToAllReports: false, approved: true, favorite: false, companyId: 12345, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, createdDate: "2026-02-20T10:15:00Z", modifiedDate: "2026-02-21T08:30:00Z", reportSuiteName: "Example Site"};
    }

    # Retrieve multiple calculated metrics
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + rsids - Filter list to only include calculated metrics tied to specified RSID list (comma-delimited)
    # + ownerId - Filter list to only include calculated metrics owned by the specified loginId
    # + filterByIds - Filter list to only include calculated metrics in the specified list (comma-delimited list of IDs) (this is the same as calculatedMetricFilter, and is overwritten by calculatedMetricFilter
    # + toBeUsedInRsid - The report suite where the calculated metric intended to be used.  This report suite will be used to determine things like compatibility and permissions.  If it is not specified then the permissions will be calculated based on the union of all metrics authorized in all groups the user belongs to.  If the compatibility expansion is specified and toBeUsedInRsid is not then the compatibility returned is based off the compatibility from the last time the calculated metric was saved
    # + locale - Locale
    # + name - Filter list to only include calculated metrics that contains the Name
    # + tagNames - Filter list to only include calculated metrics that contains one of the tags
    # + favorite - Filter list to only include calculated metrics that are favorites
    # + approved - Filter list to only include calculated metrics that are approved
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + sortDirection - Sort direction (ASC or DESC)
    # + sortProperty - Property to sort by (name, modified_date, id is currently allowed)
    # + expansion - Comma-delimited list of additional calculated metric metadata fields to include on response
    # + includeType - Include additional calculated metrics not owned by user. The "all" option takes precedence over "shared"
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Unable to retrieve list of calculated metrics shared with user)
    # http:Unauthorized (Owner filter error; user specified is not in the same company as the requesting user)
    # http:Forbidden (Requesting non-shared calculated metrics for other users is restricted to admin users)
    # http:InternalServerError (External API error; Calculated metric retrieval failed)
    resource function get [string globalCompanyId]/calculatedmetrics(string? rsids, int:Signed32? ownerId, string? filterByIds, string? toBeUsedInRsid, string? name, string? tagNames, boolean? favorite, boolean? approved, ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[]? expansion, ("all"|"shared"|"templates")[]? includeType, string locale = "en_US", int 'limit = 10, int page = 0, string sortDirection = "ASC", string sortProperty = "id") returns AnalyticsCalculatedMetric[]|CalculatedMetricErrorStatusBadRequest|CalculatedMetricErrorStatusUnauthorized|CalculatedMetricErrorStatusForbidden|CalculatedMetricErrorStatusInternalServerError {
        return [{id: "cm_1001", name: "Revenue per Visit", description: "Total revenue divided by visits", rsid: "examplersid", 'type: "CURRENCY", polarity: "positive", precision: 2, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-10T09:00:00Z", modified: "2026-01-12T11:45:00Z", categories: ["Revenue"], definition: {}}];
    }

    # Retrieve a single calculated metric by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The calculated metric ID to retrieve
    # + locale - Locale
    # + expansion - Comma-delimited list of additional calculated metric metadata fields to include on response
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:Forbidden (Requesting non-shared calculated metrics for other users is restricted to admin users)
    # http:InternalServerError (External API error; calculated metric retrieval failed)
    resource function get [string globalCompanyId]/calculatedmetrics/[string id](("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[]? expansion, string locale = "en_US") returns AnalyticsCalculatedMetric|CalculatedMetricErrorStatusForbidden|CalculatedMetricErrorStatusInternalServerError {
        return {id: "cm_1001", name: "Revenue per Visit", description: "Total revenue divided by visits", rsid: "examplersid", 'type: "CURRENCY", polarity: "positive", precision: 2, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-10T09:00:00Z", modified: "2026-01-12T11:45:00Z", categories: ["Revenue"], definition: {}};
    }

    # Retrieve user's date ranges
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + includeType - Include additional dateranges not owned by user. The "all" option takes precedence over "shared"
    # + expansion - Comma-delimited list of additional date range metadata fields to include on response
    # + locale - Locale
    # + filterByIds - Filter list to only include date ranges in the specified list (comma-delimited list of IDs)
    # + newDefinition - Use the new JSON def
    # + filterByModifiedAfter - Filter list to only include date ranges modified since this date (ISO8601 format)
    # + curatedRsid - Include the curatedItem status for given Rsid
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + return - successful operation 
    resource function get [string globalCompanyId]/dateranges(("all"|"shared"|"templates"|"curatedItem")[]? includeType, ("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[]? expansion, string? filterByIds, string? filterByModifiedAfter, string? curatedRsid, string locale = "en_US", boolean newDefinition = false, int 'limit = 10, int page = 0) returns ResponsePageExpandedDateRange {
        return {content: [{id: "dr_4001", name: "Last 30 Days", description: "Rolling 30 day window", template: false, approved: true, favorite: false, companyId: 12345, createDate: "2026-01-02T00:00:00Z", modified: "2026-01-03T00:00:00Z"}], totalElements: 1, numberOfElements: 1, totalPages: 1, size: 10, number: 0, firstPage: true, lastPage: true};
    }

    # Retrieve dimensions for a report suite
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + rsid - A report suite ID
    # + locale - Locale
    # + segmentable - Only include dimensions that are valid within a segment
    # + reportable - Only include dimensions that are valid within a report
    # + classifiable - Only include classifiable dimensions
    # + expansion - Add extra metadata to items (comma-delimited list)
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Invalid JSON input)
    # http:Unauthorized (User does not have access to this report suite)
    # http:InternalServerError (Unexpected internal server error)
    resource function get [string globalCompanyId]/dimensions(string rsid, true? segmentable, true? reportable, ("tags"|"allowedForReporting"|"attributionModel"|"categories"|"allocationType"|"expirationType"|"expirationCustomDays"|"dataType"|"bindingEvents"|"merchandisingSyntax")[]? expansion, string locale = "en_US", boolean classifiable = false) returns AnalyticsDimension[]|http:BadRequest|http:Unauthorized|http:InternalServerError {
        return [{id: "variables/page", name: "Page", title: "Page", 'type: "STRING", category: "Content", segmentable: true, reportable: ["ranked"], pathable: true, allowedForReporting: true, description: "Page name"}, {id: "variables/daterangeday", name: "Day", title: "Day", 'type: "STRING", category: "Time", segmentable: true, allowedForReporting: true, description: "Calendar day"}];
    }

    # Retrieve metrics for a report suite
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + rsid - ID of desired report suite
    # + locale - Locale that system named metrics should be returned in
    # + segmentable - Filter the metrics by if they are valid in a segment
    # + expansion - Add extra metadata to items (comma-delimited list)
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Invalid JSON input)
    # http:Forbidden (Insufficient access to perform operation)
    # http:InternalServerError (Unexpected internal server error)
    resource function get [string globalCompanyId]/metrics(string rsid, ("tags"|"allowedForReporting"|"categories")[]? expansion, string locale = "en_US", boolean segmentable = false) returns AnalyticsMetric[]|http:BadRequest|http:Forbidden|http:InternalServerError {
        return [{id: "metrics/visits", name: "Visits", title: "Visits", 'type: "INT", category: "Traffic", segmentable: true, allowedForReporting: true, calculated: false, polarity: "positive", description: "Number of visits"}];
    }

    # Retrieve user's projects
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + includeType - Include additional projects not owned by user. The "all" option takes precedence over "shared". If neither guided, or project is included, both types are returned
    # + expansion - Comma-delimited list of additional project metadata fields to include on response
    # + filterByIds - Filter list to only include projects in the specified list (comma-delimited list of IDs)
    # + locale - Locale
    # + pagination - return paginated results
    # + ownerId - Filter list to only include projects owned by the specified loginId
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + return - successful operation 
    resource function get [string globalCompanyId]/projects(("all"|"shared")[]? includeType, ("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[]? expansion, string? filterByIds, int:Signed32? ownerId, string locale = "en_US", "true"|"false" pagination = "false", int 'limit = 10, int page = 0) returns AnalyticsProject[] {
        return [{id: "p_3001", name: "Weekly Performance Dashboard", description: "Key traffic and revenue metrics", rsid: "examplersid", 'type: "project", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-15T12:00:00Z", modified: "2026-01-20T16:20:00Z", approved: true, favorite: true, accessLevel: "owner"}];
    }

    # Retrieve project configuration
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The Project id for which to retrieve information
    # + expansion - Comma-delimited list of additional project metadata fields to include on response
    # + locale - Locale
    # + return - successful operation 
    resource function get [string globalCompanyId]/projects/[string id](("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[]? expansion, string locale = "en_US") returns AnalyticsProject {
        return {id: "p_3001", name: "Weekly Performance Dashboard", description: "Key traffic and revenue metrics", rsid: "examplersid", 'type: "project", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-15T12:00:00Z", modified: "2026-01-20T16:20:00Z", approved: true, favorite: true, accessLevel: "owner"};
    }

    # Retrieve top items report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + rsid - ID of desired report suite ie. myrsid
    # + dimension - Dimension to run the report against. Example: 'variables/page'
    # + locale - Locale that system named metrics should be returned in
    # + dateRange - Format: YYYY-MM-DD/YYYY-MM-DD
    # + searchClause - General search string; wrap with single quotes. Example: 'PageABC'
    # + startDate - Format: YYYY-MM-DD
    # + endDate - Format: YYYY-MM-DD
    # + searchAnd - Search terms that will be AND-ed together. Space delimited
    # + searchOr - Search terms that will be OR-ed together. Space delimited
    # + searchNot - Search terms that will be treated as NOT including. Space delimited
    # + searchPhrase - A full search phrase that will be searched for
    # + lookupNoneValues - Controls None values to be included
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + return - returns can be any of following types 
    # http:Ok (Successful operation)
    # http:PartialContent (Partially successful operation.  Some response columns contain errors.  See the [Partial Responses](https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/reporting-guide.md#partial-responses-206-status-code) for details.)
    # http:BadRequest (Invalid input; name, rsid, and definition are all required. Definition must be formatted as a JSON Object.)
    resource function get [string globalCompanyId]/reports/topItems(string rsid, string dimension, string? dateRange, @http:Query {name: "search-clause"} string? searchClause, string? startDate, string? endDate, string? searchAnd, string? searchOr, string? searchNot, string? searchPhrase, string locale = "en_US", boolean lookupNoneValues = true, int 'limit = 10, int page = 0) returns UnhashReportData|UnhashReportDataPartialContent|ReportErrorStatusBadRequest {
        return {reportId: "top_6001", number: 0, firstPage: true, lastPage: true, numberOfElements: 2, totalPages: 1, totalElements: 2, rows: [{itemId: "1234567", value: "Home"}, {itemId: "7654321", value: "Products"}]};
    }

    # Retrieve all segments
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + rsids - Filter list to only include segments tied to specified RSID list (comma-delimited)
    # + segmentFilter - Filter list to only include segments in the specified list (comma-delimited list of IDs)
    # + locale - Locale
    # + name - Filter list to only include segments that contains the Name
    # + tagNames - Filter list to only include segments that contains one of the tags
    # + filterByPublishedSegments - Filter list to only include segments where the published field is set to one of the allowable values (all, true, false)
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + sortDirection - Sort direction (ASC or DESC
    # + sortProperty - Property to sort by (name, modified_date, id is currently allowed)
    # + expansion - Comma-delimited list of additional segment metadata fields to include on response
    # + includeType - Include additional segments not owned by user. The "all" option takes precedence over "shared"
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Unable to retrieve list of segments shared with user)
    # http:Unauthorized (Owner filter error; user specified is not in the same company as the requesting user)
    # http:Forbidden (Requesting non-shared segments for other users is restricted to admin users)
    # http:InternalServerError (External API error; Segment retrieval failed)
    resource function get [string globalCompanyId]/segments(string? rsids, string? segmentFilter, string? name, string? tagNames, ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[]? expansion, ("shared"|"all"|"templates")[]? includeType, string locale = "en_US", "all"|"true"|"false" filterByPublishedSegments = "all", int 'limit = 10, int page = 0, string sortDirection = "ASC", string sortProperty = "id") returns AnalyticsSegmentResponseItem|http:BadRequest|http:Unauthorized|http:Forbidden|http:InternalServerError {
        return {id: "s_2001", name: "Mobile Visitors", description: "Visits originating from mobile devices", rsid: "examplersid", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-05T07:00:00Z", modified: "2026-01-06T07:30:00Z", categories: ["Audience"], reportSuiteName: "Example Site"};
    }

    # Retrieve a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The segment ID to retrieve
    # + locale - Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    # + expansion - Comma-delimited list of additional segment metadata fields to include on response
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:Forbidden (Requesting non-shared segments for other users is restricted to admin users)
    # http:InternalServerError (External API error; segment retrieval failed)
    resource function get [string globalCompanyId]/segments/[string id](("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[]? expansion, string locale = "en_US") returns AnalyticsSegmentResponseItem|http:Forbidden|http:InternalServerError {
        return {id: "s_2001", name: "Mobile Visitors", description: "Visits originating from mobile devices", rsid: "examplersid", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-05T07:00:00Z", modified: "2026-01-06T07:30:00Z", categories: ["Audience"], reportSuiteName: "Example Site"};
    }

    # Retrieve users for current company
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + 'limit - Number of results per page
    # + page - Page number (base 0 - first page is "0")
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:InternalServerError (Database error or other unexpected error)
    resource function get [string globalCompanyId]/users(int 'limit = 10, int page = 0) returns AnalyticsUser[]|http:InternalServerError {
        return [{loginId: 1001, login: "jane.doe@example.com", firstName: "Jane", lastName: "Doe", fullName: "Jane Doe", email: "jane.doe@example.com", companyid: 12345, title: "Analyst", disabled: false, imsUserId: "ABCDEF@AdobeID", createDate: "2025-06-01T00:00:00Z"}];
    }

    # Retrieve current user
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + return - successful operation 
    resource function get [string globalCompanyId]/users/me() returns AnalyticsUser {
        return {loginId: 1001, login: "jane.doe@example.com", firstName: "Jane", lastName: "Doe", fullName: "Jane Doe", email: "jane.doe@example.com", companyid: 12345, title: "Analyst", disabled: false, imsUserId: "ABCDEF@AdobeID", createDate: "2025-06-01T00:00:00Z"};
    }

    # Create new annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + expansion - Comma-delimited list of additional annotation metadata fields to include on response
    # + locale - Locale
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    resource function post [string globalCompanyId]/annotations(("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[]? expansion, http:Request request, string locale = "en_US") returns AnalyticsAnnotationOk {
        return <AnalyticsAnnotationOk>{body: {id: "a1b2c3", name: "Spring Campaign Launch", description: "Marketing campaign kicked off across all channels", rsid: "examplersid", color: "STANDARD3", dateRange: "2026-03-01T00:00:00/2026-03-31T23:59:59", applyToAllReports: false, approved: true, favorite: false, companyId: 12345, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, createdDate: "2026-02-20T10:15:00Z", modifiedDate: "2026-02-21T08:30:00Z", reportSuiteName: "Example Site"}};
    }

    # Create a new calculated metric
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + locale - Locale
    # + expansion - Comma-delimited list of additional calculated metric metadata fields to include on response
    # + payload - JSON-formatted Object containing key/value pairs for calculated metric creation 
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Invalid input; name, rsid, and definition are all required. Definition must be formatted as a JSON Object.)
    # http:InternalServerError (External API error; Calculated metric create or retrieval failed)
    resource function post [string globalCompanyId]/calculatedmetrics(("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[]? expansion, @http:Payload AnalyticsCalculatedMetric payload, string locale = "en_US") returns AnalyticsCalculatedMetricOk|CalculatedMetricErrorStatusBadRequest|CalculatedMetricErrorStatusInternalServerError {
        return <AnalyticsCalculatedMetricOk>{body: {id: "cm_1001", name: "Revenue per Visit", description: "Total revenue divided by visits", rsid: "examplersid", 'type: "CURRENCY", polarity: "positive", precision: 2, owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-10T09:00:00Z", modified: "2026-01-12T11:45:00Z", categories: ["Revenue"], definition: {}}};
    }

    # Create a date range
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + expansion - Comma-delimited list of additional date range metadata fields to include on response
    # + newDefinition - Use the new JSON def
    # + locale - Locale
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    resource function post [string globalCompanyId]/dateranges(("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[]? expansion, http:Request request, boolean newDefinition = false, string locale = "en_US") returns ExpandedDateRangeOk {
        return <ExpandedDateRangeOk>{body: {id: "dr_4001", name: "Last 30 Days", description: "Rolling 30 day window", template: false, approved: true, favorite: false, companyId: 12345, createDate: "2026-01-02T00:00:00Z", modified: "2026-01-03T00:00:00Z"}};
    }

    # Create a project
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + expansion - Comma-delimited list of additional project metadata fields to include on response
    # + locale - Locale
    # + request - JSON-formatted Object containing project keys/value pairs to be updated 
    # + return - successful operation 
    resource function post [string globalCompanyId]/projects(("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[]? expansion, http:Request request, string locale = "en_US") returns AnalyticsProjectOk {
        return <AnalyticsProjectOk>{body: {id: "p_3001", name: "Weekly Performance Dashboard", description: "Key traffic and revenue metrics", rsid: "examplersid", 'type: "project", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-15T12:00:00Z", modified: "2026-01-20T16:20:00Z", approved: true, favorite: true, accessLevel: "owner"}};
    }

    # Create a report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + payload - Report request with dimension, metrics, filters and date range 
    # + return - returns can be any of following types 
    # http:Ok (Successful operation)
    # http:PartialContent (Partially successful operation.  Some response columns contain errors.  See the [Partial Responses](https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/reporting-guide.md#partial-responses-206-status-code) for details.)
    # http:BadRequest (Invalid input; name, rsid, and definition are all required. Definition must be formatted as a JSON Object.)
    resource function post [string globalCompanyId]/reports(@http:Payload RankedRequest payload) returns RankedReportDataOk|RankedReportDataPartialContent|ReportErrorStatusBadRequest {
        return <RankedReportDataOk>{body: {reportId: "r_5001", number: 0, firstPage: true, lastPage: true, numberOfElements: 2, totalPages: 1, totalElements: 2, rows: [{rowId: "1", itemId: "1234567", value: "Home", data: [1250, 3400]}, {rowId: "2", itemId: "7654321", value: "Products", data: [980, 2100]}], columns: {columnIds: ["0", "1"]}}};
    }

    # Create a realtime report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + payload - Realtime report request with dimension, metrics and filters 
    # + return - returns can be any of following types 
    # http:Ok (Successful operation)
    # http:PartialContent (Partially successful operation.  Some response columns contain errors.  See the [Partial Responses](https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/reporting-guide.md#partial-responses-206-status-code) for details.)
    # http:BadRequest (Invalid input; name, rsid, and definition are all required. Definition must be formatted as a JSON Object.)
    resource function post [string globalCompanyId]/reports/realtime(@http:Payload RankedRequest payload) returns RankedReportDataOk|RankedReportDataPartialContent|ReportErrorStatusBadRequest {
        return <RankedReportDataOk>{body: {reportId: "r_5001", number: 0, firstPage: true, lastPage: true, numberOfElements: 2, totalPages: 1, totalElements: 2, rows: [{rowId: "1", itemId: "1234567", value: "Home", data: [1250, 3400]}, {rowId: "2", itemId: "7654321", value: "Products", data: [980, 2100]}], columns: {columnIds: ["0", "1"]}}};
    }

    # Create a segment
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + locale - Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    # + expansion - Comma-delimited list of additional segment metadata fields to include on response
    # + payload - JSON-formatted Object containing key/value pairs for segment creation 
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Invalid input; name, rsid, and definition are all required. Definition must be formatted as a JSON Object.)
    # http:InternalServerError (External API error; Segment create or retrieval failed)
    resource function post [string globalCompanyId]/segments(("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[]? expansion, @http:Payload AnalyticsSegment payload, string locale = "en_US") returns AnalyticsSegmentResponseItemOk|http:BadRequest|http:InternalServerError {
        return <AnalyticsSegmentResponseItemOk>{body: {id: "s_2001", name: "Mobile Visitors", description: "Visits originating from mobile devices", rsid: "examplersid", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-05T07:00:00Z", modified: "2026-01-06T07:30:00Z", categories: ["Audience"], reportSuiteName: "Example Site"}};
    }

    # Update a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Segment ID to be updated
    # + locale - Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    # + expansion - Comma-delimited list of additional segment metadata fields to include on response
    # + payload - JSON-formatted Object containing key/value pairs to be updated 
    # + return - returns can be any of following types 
    # http:Ok (successful operation)
    # http:BadRequest (Definition must be formatted as a JSON Object)
    # http:Unauthorized (Company mismatch; segment ownership can only be transferred within the same organization)
    # http:Forbidden (User does not have permission to update this segment)
    # http:InternalServerError (External API error; Segment update or retrieval failed)
    resource function put [string globalCompanyId]/segments/[string id](("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[]? expansion, @http:Payload record {|record {}...;|} payload, string locale = "en_US") returns AnalyticsSegmentResponseItem|http:BadRequest|http:Unauthorized|http:Forbidden|http:InternalServerError {
        return {id: "s_2001", name: "Mobile Visitors", description: "Visits originating from mobile devices", rsid: "examplersid", owner: {id: 1001, name: "Jane Doe", login: "jane.doe@example.com"}, created: "2026-01-05T07:00:00Z", modified: "2026-01-06T07:30:00Z", categories: ["Audience"], reportSuiteName: "Example Site"};
    }
}

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type AnalyticsAnnotationOk record {|
    *http:Ok;
    AnalyticsAnnotation body;
|};

public type AnalyticsCalculatedMetricOk record {|
    *http:Ok;
    AnalyticsCalculatedMetric body;
|};

public type AnalyticsProjectOk record {|
    *http:Ok;
    AnalyticsProject body;
|};

public type AnalyticsSegmentResponseItemOk record {|
    *http:Ok;
    AnalyticsSegmentResponseItem body;
|};

public type CalculatedMetricErrorStatusBadRequest record {|
    *http:BadRequest;
    CalculatedMetricErrorStatus body;
|};

public type CalculatedMetricErrorStatusForbidden record {|
    *http:Forbidden;
    CalculatedMetricErrorStatus body;
|};

public type CalculatedMetricErrorStatusInternalServerError record {|
    *http:InternalServerError;
    CalculatedMetricErrorStatus body;
|};

public type ExpandedDateRangeOk record {|
    *http:Ok;
    ExpandedDateRange body;
|};

public type RankedReportDataOk record {|
    *http:Ok;
    RankedReportData body;
|};

public type RankedReportDataPartialContent record {|
    *http:PartialContent;
    RankedReportData body;
|};

public type ReportErrorStatusBadRequest record {|
    *http:BadRequest;
    ReportErrorStatus body;
|};

public type UnhashReportDataPartialContent record {|
    *http:PartialContent;
    UnhashReportData body;
|};

public type CalculatedMetricErrorStatus record {
    string errorDescription?;
    string rootCauseService?;
    "no_feature_access_to_advanced_calculated_metrics"|"invalid_metric_access"|"method_not_allowed"|"resource_conflict"|"invalid_access"|"resource_temporarily_unavailable"|"external_api_failure"|"aam_failure"|"resource_already_exists"|"invalid_state"|"invalid_json_input"|"invalid_parameters"|"invalid_dimension_access"|"unsupported_data_type"|"resource_not_found"|"insufficient_access"|"health_check_error"|"invalid_data"|"unexpected_error"|"external_api_error"|"unsupported_resource"|"io_error"|"invalid_request"|"invalid_client_id"|"unauthorized"|"authorization_error"|"invalid_token"|"insufficient_scope"|"bluecoat_unauthorized" errorCode?;
    string errorId?;
    record {|record {}...;|} errorDetails?;
};

public type ReportErrorStatus record {
    string errorDescription?;
    string rootCauseService?;
    "invalid_segment_ids_found"|"invalid_metric_access"|"method_not_allowed"|"resource_conflict"|"invalid_access"|"resource_temporarily_unavailable"|"external_api_failure"|"aam_failure"|"resource_already_exists"|"invalid_state"|"invalid_json_input"|"invalid_parameters"|"invalid_dimension_access"|"unsupported_data_type"|"resource_not_found"|"insufficient_access"|"health_check_error"|"invalid_data"|"unexpected_error"|"external_api_error"|"unsupported_resource"|"io_error"|"invalid_request"|"invalid_client_id"|"unauthorized"|"authorization_error"|"invalid_token"|"insufficient_scope"|"bluecoat_unauthorized" errorCode?;
    string errorId?;
    record {|record {}...;|} errorDetails?;
};

public type CalculatedMetricErrorStatusUnauthorized record {|
    *http:Unauthorized;
    CalculatedMetricErrorStatus body;
|};
