// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string serviceUrl = isLiveServer ? "https://analytics.adobe.io/api" : "http://localhost:9090";
final string accessToken = isLiveServer ? os:getEnv("ADOBE_ANALYTICS_ACCESS_TOKEN") : "test_token";
final string apiKey = isLiveServer ? os:getEnv("ADOBE_ANALYTICS_API_KEY") : "test_api_key";
final string companyId = isLiveServer ? os:getEnv("ADOBE_ANALYTICS_COMPANY_ID") : "examplecompany";
final string reportSuiteId = isLiveServer ? os:getEnv("ADOBE_ANALYTICS_RSID") : "examplersid";

final Client adobeClient = check new (
    {authorization: "Bearer " + accessToken, xApiKey: apiKey},
    {httpVersion: isLiveServer ? http:HTTP_2_0 : http:HTTP_1_1},
    serviceUrl
);

function jsonRequest(json body) returns http:Request {
    http:Request req = new;
    req.setJsonPayload(body);
    return req;
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListAnnotations() returns error? {
    ResponsePageAnalyticsAnnotation response = check adobeClient->listAnnotations(companyId);
    AnalyticsAnnotation[] annotations = response.content ?: [];
    test:assertTrue(annotations.length() > 0);
    test:assertTrue(annotations[0]?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateAnnotation() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsAnnotation response = check adobeClient->createAnnotation(companyId, jsonRequest({name: "Test annotation", rsid: reportSuiteId}));
    test:assertTrue(response?.name is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetAnnotation() returns error? {
    AnalyticsAnnotation response = check adobeClient->getAnnotation(companyId, "a1b2c3");
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteAnnotation() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsAnnotation created = check adobeClient->createAnnotation(companyId, jsonRequest({name: "Annotation to delete", rsid: reportSuiteId}));
    DeleteResponse response = check adobeClient->deleteAnnotation(companyId, <string>created?.id);
    test:assertTrue(response?.result is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testFindCalculatedMetrics() returns error? {
    AnalyticsCalculatedMetric[] response = check adobeClient->findCalculatedMetrics(companyId);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateCalculatedMetric() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsCalculatedMetric response = check adobeClient->createCalculatedMetric(companyId, {name: "Revenue per Visit", rsid: reportSuiteId, definition: {}});
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testFindOneCalculatedMetric() returns error? {
    AnalyticsCalculatedMetric response = check adobeClient->findOneCalculatedMetric(companyId, "cm_1001");
    test:assertTrue(response?.name is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteCalculatedMetric() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsCalculatedMetric created = check adobeClient->createCalculatedMetric(companyId, {name: "Metric to delete", rsid: reportSuiteId, definition: {}});
    DeleteResponse response = check adobeClient->deleteCalculatedMetric(companyId, <string>created?.id);
    test:assertTrue(response?.result is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetAllSegments() returns error? {
    AnalyticsSegmentResponseItem response = check adobeClient->getAllSegments(companyId);
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateSegment() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsSegmentResponseItem response = check adobeClient->createSegment(companyId, {name: "Mobile Visitors", rsid: reportSuiteId});
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetSegment() returns error? {
    AnalyticsSegmentResponseItem response = check adobeClient->getSegment(companyId, "s_2001");
    test:assertTrue(response?.name is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testUpdateSegment() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsSegmentResponseItem response = check adobeClient->updateSegment(companyId, "s_2001", {"definition": {}});
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testDeleteSegment() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsSegmentResponseItem created = check adobeClient->createSegment(companyId, {name: "Segment to delete", rsid: reportSuiteId});
    string response = check adobeClient->deleteSegment(companyId, <string>created?.id);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetProjectsOfUser() returns error? {
    AnalyticsProject[] response = check adobeClient->getProjectsOfUser(companyId);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateProject() returns error? {
    if isLiveServer {
        return;
    }
    AnalyticsProject response = check adobeClient->createProject(companyId, jsonRequest({name: "Weekly Performance Dashboard", rsid: reportSuiteId}));
    test:assertTrue(response?.id is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetProjectConfiguration() returns error? {
    AnalyticsProject response = check adobeClient->getProjectConfiguration(companyId, "p_3001");
    test:assertTrue(response?.name is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetDimensionsForReportSuite() returns error? {
    AnalyticsDimension[] response = check adobeClient->getDimensionsForReportSuite(companyId, rsid = reportSuiteId);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetMetricsForReportSuite() returns error? {
    AnalyticsMetric[] response = check adobeClient->getMetricsForReportSuite(companyId, rsid = reportSuiteId);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testRunReport() returns error? {
    RankedReportData response = check adobeClient->runReport(companyId, {
        rsid: reportSuiteId,
        dimension: "variables/page",
        settings: {'limit: 10}
    });
    test:assertTrue(response?.reportId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testRunRealtimeReport() returns error? {
    RankedReportData response = check adobeClient->runRealtimeReport(companyId, {
        rsid: reportSuiteId,
        dimension: "variables/page",
        settings: {'limit: 10}
    });
    test:assertTrue(response?.reportId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testRunTopItemReport() returns error? {
    UnhashReportData response = check adobeClient->runTopItemReport(companyId, rsid = reportSuiteId, dimension = "variables/page");
    test:assertTrue(response?.reportId is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetCurrentUser() returns error? {
    AnalyticsUser response = check adobeClient->getCurrentUser(companyId);
    test:assertTrue(response?.login is string);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testListAllUsersForCompany() returns error? {
    AnalyticsUser[] response = check adobeClient->listAllUsersForCompany(companyId);
    test:assertTrue(response.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testGetDateRangesForUser() returns error? {
    ResponsePageExpandedDateRange response = check adobeClient->getDateRangesForUser(companyId);
    ExpandedDateRange[] dateRanges = response.content ?: [];
    test:assertTrue(dateRanges.length() > 0);
    test:assertTrue(dateRanges[0]?.id is string);
    test:assertEquals(response?.totalElements, 1);
    test:assertEquals(response?.firstPage, true);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testCreateDateRange() returns error? {
    if isLiveServer {
        return;
    }
    ExpandedDateRange response = check adobeClient->createDateRange(companyId, jsonRequest({name: "Last 30 Days"}));
    test:assertTrue(response?.id is string);
}
