// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The endpoints described here are routed through analytics.adobe.io. In order to use these endpoints you must create an oAuth client that is subscribed to access the Adobe Analytics Reporting API. 
# 
#  To view the API References for non-core Analytics 2.0 APIs, select the **API Reference** drop-down menu at the top of the page. 
# 
#  Note: Adobe may add optional request and response members (name/value pairs) to existing API objects at any time and without notice or changes in versioning. Adobe recommends that you refer to the API documentation of any third-party tool you integrate with our APIs so that such additions are ignored in processing if not understood. If implemented properly, such additions are non-breaking changes for your implementation. Adobe will not remove parameters or add required parameters without first providing standard notification through release notes.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://analytics.adobe.io/api") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Retrieve all annotations.
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function listAnnotations(string globalCompanyId, map<string|string[]> headers = {}, *ListAnnotationsQueries queries) returns ResponsePageAnalyticsAnnotation|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/annotations`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}, "includeType": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create new annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function createAnnotation(string globalCompanyId, http:Request request, map<string|string[]> headers = {}, *CreateAnnotationQueries queries) returns AnalyticsAnnotation|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/annotations`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get existing annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Annotation ID to retrieve
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getAnnotation(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetAnnotationQueries queries) returns AnalyticsAnnotation|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/annotations/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update existing annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Annotation ID to update
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function updateAnnotation(string globalCompanyId, string id, http:Request request, map<string|string[]> headers = {}, *UpdateAnnotationQueries queries) returns AnalyticsAnnotation|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/annotations/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete existing annotation
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Annotation ID to update
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteAnnotation(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteAnnotationQueries queries) returns DeleteResponse|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/annotations/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve multiple calculated metrics
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function findCalculatedMetrics(string globalCompanyId, map<string|string[]> headers = {}, *FindCalculatedMetricsQueries queries) returns AnalyticsCalculatedMetric[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}, "includeType": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a new calculated metric
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs for calculated metric creation 
    # + return - successful operation 
    remote isolated function createCalculatedMetric(string globalCompanyId, AnalyticsCalculatedMetric payload, map<string|string[]> headers = {}, *CreateCalculatedMetricQueries queries) returns AnalyticsCalculatedMetric|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve calculated metric functions
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getCalculatedMetricFunctions(string globalCompanyId, map<string|string[]> headers = {}, *GetCalculatedMetricFunctionsQueries queries) returns CalcMetricFunction[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/functions`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve a calculated metric function by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The function ID to retrieve
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getCalculatedMetricFunction(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetCalculatedMetricFunctionQueries queries) returns CalcMetricFunction|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/functions/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Validate a calculated metric definition
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs for calculated metric validation 
    # + return - successful operation 
    remote isolated function validateCalculatedMetric(string globalCompanyId, AnalyticsCalculatedMetric payload, map<string|string[]> headers = {}, *ValidateCalculatedMetricQueries queries) returns AnalyticsCalculatedMetric|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/validate`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve a single calculated metric by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The calculated metric ID to retrieve
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function findOneCalculatedMetric(string globalCompanyId, string id, map<string|string[]> headers = {}, *FindOneCalculatedMetricQueries queries) returns AnalyticsCalculatedMetric|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update an existing calculated metric
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Calculated Metric ID to be updated
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs to be updated 
    # + return - successful operation 
    remote isolated function updateCalculatedMetric(string globalCompanyId, string id, AnalyticsCalculatedMetric payload, map<string|string[]> headers = {}, *UpdateCalculatedMetricQueries queries) returns AnalyticsCalculatedMetric|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete calculated metrics by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The calculated metric ID to be deleted
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteCalculatedMetric(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteCalculatedMetricQueries queries) returns DeleteResponse|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/calculatedmetrics/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve components shared by user
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function findAllSharesForCompany(string globalCompanyId, map<string|string[]> headers = {}, *FindAllSharesForCompanyQueries queries) returns Share[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares`;
        map<Encoding> queryParamEncoding = {"includeType": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update shared components with users
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted ARRAY of objects containing key-value pairs that conform to the schema 
    # + return - successful operation 
    remote isolated function updateSharesForComponents(string globalCompanyId, SharedComponent[] payload, map<string|string[]> headers = {}, *UpdateSharesForComponentsQueries queries) returns SharedComponent|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Share component with user
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Share object containing key-value pairs that conform to the Share schema 
    # + return - successful operation 
    remote isolated function saveShareMyCompany(string globalCompanyId, Share payload, map<string|string[]> headers = {}, *SaveShareMyCompanyQueries queries) returns Share|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create search for shared components
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - items to search for 
    # + return - successful operation 
    remote isolated function searchComponentShares(string globalCompanyId, ComponentSearch payload, map<string|string[]> headers = {}, *SearchComponentSharesQueries queries) returns SavedSharedComponent|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares/component/search`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve details of share by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The share ID to return details for
    # + headers - Headers to be sent with the request 
    # + return - successful operation 
    remote isolated function getShareById(string globalCompanyId, string id, map<string|string[]> headers = {}) returns Share|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares/${getEncodedUri(id)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Delete share by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The shareId to be deleted
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteShare(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteShareQueries queries) returns record {|record {}...;|}|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve component IDs shared with user
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getComponentsSharedToMe(string globalCompanyId, map<string|string[]> headers = {}, *GetComponentsSharedToMeQueries queries) returns string[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/shares/sharedto/me`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create search for component tags
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - items to search for 
    # + return - successful operation 
    remote isolated function searchComponentTags(string globalCompanyId, ComponentSearch payload, map<string|string[]> headers = {}, *SearchComponentTagsQueries queries) returns TaggedComponent|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/component/search`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve tags for current user company
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function findAllTagsForCompany(string globalCompanyId, map<string|string[]> headers = {}, *FindAllTagsForCompanyQueries queries) returns Tag[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create tags for current user company
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + payload - JSON-formatted array of Tag objects containing key-value pairs 
    # + return - successful operation 
    remote isolated function saveTagListForCompany(string globalCompanyId, Tag[] payload, map<string|string[]> headers = {}) returns Tag[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Delete tags from components
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteTagItemsFromComponents(string globalCompanyId, map<string|string[]> headers = {}, *DeleteTagItemsFromComponentsQueries queries) returns record {|record {}...;|}[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve component tags by component ID and component type
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getTagListByComponentIdAndComponentType(string globalCompanyId, map<string|string[]> headers = {}, *GetTagListByComponentIdAndComponentTypeQueries queries) returns Tag[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/search`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update tags for component
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + payload - JSON-formatted object containing key-value pairs that conform to the schema 
    # + return - successful operation 
    remote isolated function saveTagComponentList(string globalCompanyId, TaggedComponent[] payload, map<string|string[]> headers = {}) returns TaggedComponent[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/tagitems`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Retrieve tag by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Tag ID to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - successful operation 
    remote isolated function getTagById(string globalCompanyId, int:Signed32 id, map<string|string[]> headers = {}) returns Tag|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/${getEncodedUri(id)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Delete tag from component
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The tagId to be deleted
    # + headers - Headers to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteTag(string globalCompanyId, int:Signed32 id, map<string|string[]> headers = {}) returns record {|record {}...;|}[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/${getEncodedUri(id)}`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve component IDs associated with tag names
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getComponentsByTagName(string globalCompanyId, map<string|string[]> headers = {}, *GetComponentsByTagNameQueries queries) returns string[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/componentmetadata/tags/tagnames`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve configuration for a date range
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The DateRange id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getDateRange(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetDateRangeQueries queries) returns ExpandedDateRange|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dateranges/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update configuration for a date range
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The DateRange id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function updateDateRange(string globalCompanyId, string id, http:Request request, map<string|string[]> headers = {}, *UpdateDateRangeQueries queries) returns ExpandedDateRange|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dateranges/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a date range
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The DateRange id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteDateRange(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteDateRangeQueries queries) returns DeleteResponse|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dateranges/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve user's date ranges
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getDateRangesForUser(string globalCompanyId, map<string|string[]> headers = {}, *GetDateRangesForUserQueries queries) returns ResponsePageExpandedDateRange|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dateranges`;
        map<Encoding> queryParamEncoding = {"includeType": {style: FORM, explode: false}, "expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a date range
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing date range keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function createDateRange(string globalCompanyId, http:Request request, map<string|string[]> headers = {}, *CreateDateRangeQueries queries) returns ExpandedDateRange|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dateranges`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve dimensions for a report suite
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getDimensionsForReportSuite(string globalCompanyId, map<string|string[]> headers = {}, *GetDimensionsForReportSuiteQueries queries) returns AnalyticsDimension[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dimensions`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve a dimension by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The dimension ID. For example a valid id is a value like 'evar1'
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getDimensionForReportSuite(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetDimensionForReportSuiteQueries queries) returns AnalyticsDimension|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/dimensions/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve metrics for a report suite
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getMetricsForReportSuite(string globalCompanyId, map<string|string[]> headers = {}, *GetMetricsForReportSuiteQueries queries) returns AnalyticsMetric[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/metrics`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve a metric by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The id of the metric for which to retrieve info. Note ids are values like pageviews, not metrics/pageviews
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getMetricForReportSuite(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetMetricForReportSuiteQueries queries) returns AnalyticsMetric|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/metrics/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve project configuration
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The Project id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getProjectConfiguration(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetProjectConfigurationQueries queries) returns AnalyticsProject|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update a project configuration
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The Project id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing project keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function updateProjectConfiguration(string globalCompanyId, string id, http:Request request, map<string|string[]> headers = {}, *UpdateProjectConfigurationQueries queries) returns AnalyticsProject|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a project
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The Project id for which to retrieve information
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteProject(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteProjectQueries queries) returns DeleteResponse|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Creates a valid project definition
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs for Project validation 
    # + return - successful operation 
    remote isolated function validateProjectDefinition(string globalCompanyId, AnalyticsProject payload, map<string|string[]> headers = {}, *ValidateProjectDefinitionQueries queries) returns ProjectCompatibility|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects/validate`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve user's projects
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getProjectsOfUser(string globalCompanyId, map<string|string[]> headers = {}, *GetProjectsOfUserQueries queries) returns AnalyticsProject[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects`;
        map<Encoding> queryParamEncoding = {"includeType": {style: FORM, explode: false}, "expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a project
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + request - JSON-formatted Object containing project keys/value pairs to be updated 
    # + return - successful operation 
    remote isolated function createProject(string globalCompanyId, http:Request request, map<string|string[]> headers = {}, *CreateProjectQueries queries) returns AnalyticsProject|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/projects`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        // TODO: Update the request as needed;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create a report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + payload - Report request with dimension, metrics, filters and date range 
    # + return - Successful operation 
    remote isolated function runReport(string globalCompanyId, RankedRequest payload, map<string|string[]> headers = {}) returns RankedReportData|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/reports`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create a realtime report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + payload - Realtime report request with dimension, metrics and filters 
    # + return - Successful operation 
    remote isolated function runRealtimeReport(string globalCompanyId, RankedRequest payload, map<string|string[]> headers = {}) returns RankedReportData|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/reports/realtime`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve top items report
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Successful operation 
    remote isolated function runTopItemReport(string globalCompanyId, map<string|string[]> headers = {}, *RunTopItemReportQueries queries) returns UnhashReportData|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/reports/topItems`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve all segments
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getAllSegments(string globalCompanyId, map<string|string[]> headers = {}, *GetAllSegmentsQueries queries) returns AnalyticsSegmentResponseItem|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}, "includeType": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a segment
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs for segment creation 
    # + return - successful operation 
    remote isolated function createSegment(string globalCompanyId, AnalyticsSegment payload, map<string|string[]> headers = {}, *CreateSegmentQueries queries) returns AnalyticsSegmentResponseItem|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create validation for segment
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Segment definition 
    # + return - successful operation 
    remote isolated function validateSegment(string globalCompanyId, AnalyticsSegmentDefinition payload, map<string|string[]> headers = {}, *ValidateSegmentQueries queries) returns SegmentCompatibility|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments/validate`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Retrieve a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The segment ID to retrieve
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function getSegment(string globalCompanyId, string id, map<string|string[]> headers = {}, *GetSegmentQueries queries) returns AnalyticsSegmentResponseItem|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Update a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - Segment ID to be updated
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON-formatted Object containing key/value pairs to be updated 
    # + return - successful operation 
    remote isolated function updateSegment(string globalCompanyId, string id, record {|record {}...;|} payload, map<string|string[]> headers = {}, *UpdateSegmentQueries queries) returns AnalyticsSegmentResponseItem|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments/${getEncodedUri(id)}`;
        map<Encoding> queryParamEncoding = {"expansion": {style: FORM, explode: false}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Delete a segment by ID
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + id - The segment ID to be deleted
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function deleteSegment(string globalCompanyId, string id, map<string|string[]> headers = {}, *DeleteSegmentQueries queries) returns string|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/segments/${getEncodedUri(id)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Retrieve users for current company
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - successful operation 
    remote isolated function listAllUsersForCompany(string globalCompanyId, map<string|string[]> headers = {}, *ListAllUsersForCompanyQueries queries) returns AnalyticsUser[]|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/users`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve current user
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + return - successful operation 
    remote isolated function getCurrentUser(string globalCompanyId, map<string|string[]> headers = {}) returns AnalyticsUser|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/users/me`;
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Retrieve logs for provided search criteria
    #
    # + globalCompanyId - The Global Company ID for the Adobe Analytics organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - External API Error; Data could not be retrieved 
    remote isolated function getUsageAccessLogs(string globalCompanyId, map<string|string[]> headers = {}, *GetUsageAccessLogsQueries queries) returns ResponsePageUsageLogDto|error {
        string resourcePath = string `/${getEncodedUri(globalCompanyId)}/auditlogs/usage`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Authorization"] = self.apiKeyConfig.authorization;
        headerValues["x-api-key"] = self.apiKeyConfig.xApiKey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
