// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public type AnalyticsMetric record {
    string extraTitleInfo?;
    boolean allocation?;
    int:Signed32 precision?;
    string description?;
    boolean allowedForReporting?;
    string title?;
    "STRING"|"INT"|"DECIMAL"|"CURRENCY"|"PERCENT"|"TIME"|"ENUM"|"ORDERED_ENUM" 'type?;
    Tag[] tags?;
    string helpLink?;
    boolean segmentable?;
    string name?;
    string id?;
    string[] categories?;
    string category?;
    string[] support?;
    boolean calculated?;
    "positive"|"negative" polarity?;
};

public type Owner record {
    # the friendly full login name of the owner, included when the expansion parameter ownerFullName is true
    string name?;
    # the login id of the owner
    int:Signed32 id;
    # the friendly full login name of the owner, included when the expansion parameter ownerFullName is true
    string login?;
};

public type CalcMetricFunctionDef record {
    string func?;
    record {|record {}...;|} formula?;
    CalcMetricFunctionParameter[] parameters?;
    int:Signed32[] version?;
};

public type RankedReportData record {
    int:Signed32 number?;
    RankedRequest request?;
    boolean firstPage?;
    boolean lastPage?;
    int:Signed32 numberOfElements?;
    string reportId?;
    RankedColumnMetaData columns?;
    int:Signed32 totalPages?;
    string message?;
    Row[] rows?;
    RankedSummaryData summaryData?;
    int:Signed32 totalElements?;
};

# Represents the Queries record for the operation: createDateRange
public type CreateDateRangeQueries record {
    # Locale
    string locale = "en_US";
    # Use the new JSON def
    boolean newDefinition = false;
    # Comma-delimited list of additional date range metadata fields to include on response
    ("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[] expansion?;
};

public type JsonNode record {
    boolean integralNumber?;
    boolean double?;
    boolean valueNode?;
    boolean floatingPointNumber?;
    boolean bigInteger?;
    boolean 'float?;
    "ARRAY"|"BINARY"|"BOOLEAN"|"MISSING"|"NULL"|"NUMBER"|"OBJECT"|"POJO"|"STRING" nodeType?;
    boolean 'int?;
    boolean long?;
    boolean textual?;
    boolean missingNode?;
    boolean pojo?;
    boolean number?;
    boolean 'boolean?;
    boolean 'null?;
    boolean array?;
    boolean binary?;
    boolean containerNode?;
    boolean short?;
    boolean bigDecimal?;
    boolean 'object?;
};

# Represents the Queries record for the operation: deleteShare
public type DeleteShareQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: getComponentsByTagName
public type GetComponentsByTagNameQueries record {
    # The component type to operate on
    "segment"|"dashboard"|"bookmark"|"calculatedMetric"|"project"|"dateRange"|"metric"|"dimension"|"virtualReportSuite"|"scheduledJob"|"alert"|"classificationSet" componentType;
    # Comma separated list of tag names
    string tagNames;
};

# Represents the Queries record for the operation: getComponentsSharedToMe
public type GetComponentsSharedToMeQueries record {
    # ComponentType to return
    string componentType;
};

public type ResponsePageUsageLogDto record {
    int:Signed32 number?;
    boolean lastPage?;
    int numberOfElements?;
    boolean firstPage?;
    int:Signed32 size?;
    int:Signed32 totalPages?;
    string sort?;
    UsageLogDto[] content?;
    int totalElements?;
};

public type CalcMetricFunction record {
    # Calculated Metric Function example key
    string exampleKey?;
    # Calculated Metric Function name
    string name?;
    # Calculated Metric Function namespace
    string namespace?;
    # Calculated Metric Function description
    string description?;
    # If a Calculated Metric Function is persistable
    boolean persistable?;
    CalcMetricFunctionDef definition?;
    # Calculated Metric Function ID
    string id?;
    # Calculated Metric Function category
    string category?;
    # Calculated Metric Function example
    string example?;
};

# Represents the Queries record for the operation: getDateRange
public type GetDateRangeQueries record {
    # Locale
    string locale = "en_US";
    # Use the new JSON def
    boolean newDefinition = false;
    # Comma-delimited list of additional date range metadata fields to include on response
    ("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[] expansion?;
};

public type SharedComponent record {
    SharedToEntity[] shares?;
    string componentType?;
    string componentId?;
};

# Represents the Queries record for the operation: deleteCalculatedMetric
public type DeleteCalculatedMetricQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: findOneCalculatedMetric
public type FindOneCalculatedMetricQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional calculated metric metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[] expansion?;
};

public type AnalyticsSegmentResponseItem record {
    Owner owner?;
    string created?;
    # A name for the report suite.  This is deprecated and should use the report suite name instead
    string siteTitle?;
    # A description of the segment
    string description?;
    # The report suite id
    string rsid?;
    # All existing tags associated with the segment
    Tag[] tags?;
    # The friendly name for the report suite id
    string reportSuiteName?;
    # A name for the segment
    string name?;
    string modified?;
    AnalyticsSegmentDefinition definition?;
    # Id of the segment
    string id?;
    string[] categories?;
    SegmentCompatibility compatibility?;
    string definitionLastModified?;
};

public type ReportFilter record {
    string itemId?;
    AnalyticsSegmentDefinition segmentDefinition?;
    string dateRange?;
    string[] itemIds?;
    string segmentId?;
    string dateRangeRelative?;
    string id?;
    "dateRange"|"breakdown"|"segment"|"excludeItemIds" 'type?;
    string[] excludeItemIds?;
    string dimension?;
};

# Represents the Queries record for the operation: searchComponentShares
public type SearchComponentSharesQueries record {
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional project metadata fields to include on response
    ("sharesFullName")[] expansion?;
};

public type ReportDimension record {
    string id?;
    "STRING"|"INT"|"DECIMAL"|"CURRENCY"|"PERCENT"|"TIME"|"ENUM"|"ORDERED_ENUM" 'type?;
};

# Represents the Queries record for the operation: createSegment
public type CreateSegmentQueries record {
    # Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    string locale = "en_US";
    # Comma-delimited list of additional segment metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[] expansion?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Queries record for the operation: updateSharesForComponents
public type UpdateSharesForComponentsQueries record {
    # Use caching for faster requests
    boolean useCache = true;
    # Locale
    string locale = "en_US";
};

public type AnalyticsUser record {
    string lastName?;
    int:Signed32 loginId?;
    string fullName?;
    string lastAccess?;
    string login?;
    string title?;
    boolean changePassword?;
    string firstName?;
    int:Signed32 companyid?;
    string phoneNumber?;
    boolean disabled?;
    string imsUserId?;
    string tempLoginEnd?;
    string email?;
    string createDate?;
};

public type AnalyticsDimension record {
    string extraTitleInfo?;
    string parent?;
    # The configured expiration type for the eVar, determining how long the value persists across hits
    "visit"|"page_view"|"never"|"minute"|"hour"|"day"|"week"|"month"|"quarter"|"year"|"purchase"|"product_view"|"cart_open"|"cart_checkout"|"cart_add"|"cart_remove"|"cart_view"|"event" expirationType?;
    # Metric IDs that trigger merchandising binding. Populated only for merchandising eVars configured with event triggers
    string[] bindingEvents?;
    boolean pathable?;
    # The eVar storage type
    "text"|"counter" dataType?;
    # Merchandising binding style. Populated only for merchandising eVars
    "product"|"conversion_variable" merchandisingSyntax?;
    string description?;
    boolean allowedForReporting?;
    string[] reportable?;
    string title?;
    "STRING"|"INT"|"DECIMAL"|"CURRENCY"|"PERCENT"|"TIME"|"ENUM"|"ORDERED_ENUM" 'type?;
    # The configured allocation type for the eVar. Preserves distinctions collapsed by attributionModel.func
    "most_recent_last"|"original_value_first"|"linear"|"linear_to_items"|"merchandising_first"|"merchandising_last" allocationType?;
    # Number of days in the expiration window. Semantically meaningful when expirationType is 'day'
    int expirationCustomDays?;
    Tag[] tags?;
    record {|record {}...;|} attributionModel?;
    NoneSettings noneSettings?;
    boolean segmentable?;
    string name?;
    string id?;
    string[] categories?;
    string category?;
    string[] support?;
    # High-level allocation bucket. Returned automatically when expansion=attributionModel is requested; does not have its own expansion flag
    "first"|"last"|"merchandising" ecomAllocationType?;
};

# Represents the Queries record for the operation: createAnnotation
public type CreateAnnotationQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional annotation metadata fields to include on response
    ("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[] expansion?;
};

public type ScopeFilter record {
    string componentType?;
    string dimensionType?;
    string[] terms?;
    string id?;
    string operator?;
};

# Represents the Queries record for the operation: getMetricsForReportSuite
public type GetMetricsForReportSuiteQueries record {
    # Filter the metrics by if they are valid in a segment
    boolean segmentable = false;
    # ID of desired report suite
    string rsid;
    # Locale that system named metrics should be returned in
    string locale = "en_US";
    # Add extra metadata to items (comma-delimited list)
    ("tags"|"allowedForReporting"|"categories")[] expansion?;
};

public type AnnotationScope record {
    ScopeMetric[] metrics?;
    ScopeFilter[] filters?;
};

# Represents the Queries record for the operation: deleteProject
public type DeleteProjectQueries record {
    # Locale
    string locale = "en_US";
};

public type RowItem record {
    string itemId?;
    string value?;
};

# Represents the Queries record for the operation: getAnnotation
public type GetAnnotationQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional annotation metadata fields to include on response
    ("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[] expansion?;
};

# Represents the Queries record for the operation: getDimensionsForReportSuite
public type GetDimensionsForReportSuiteQueries record {
    # Only include dimensions that are valid within a segment
    true segmentable?;
    # Only include classifiable dimensions
    boolean classifiable = false;
    # A report suite ID
    string rsid;
    # Only include dimensions that are valid within a report
    true reportable?;
    # Locale
    string locale = "en_US";
    # Add extra metadata to items (comma-delimited list)
    ("tags"|"allowedForReporting"|"attributionModel"|"categories"|"allocationType"|"expirationType"|"expirationCustomDays"|"dataType"|"bindingEvents"|"merchandisingSyntax")[] expansion?;
};

# Represents the Queries record for the operation: getProjectsOfUser
public type GetProjectsOfUserQueries record {
    # return paginated results
    "true"|"false" pagination = "false";
    # Include additional projects not owned by user. The "all" option takes precedence over "shared". If neither guided, or project is included, both types are returned
    ("all"|"shared")[] includeType?;
    # Filter list to only include projects in the specified list (comma-delimited list of IDs)
    string filterByIds?;
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Locale
    string locale = "en_US";
    # Filter list to only include projects owned by the specified loginId
    int:Signed32 ownerId?;
    # Comma-delimited list of additional project metadata fields to include on response
    ("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[] expansion?;
};

public type AnalyticsSegmentDefinition record {
    AnalyticsSegmentDefinitionContainer container?;
    string func?;
    int:Signed32[] version?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # The access token from the Adobe Analytics API client integration, prefixed with "Bearer ".
    @display {label: "", kind: "password"}
    string authorization;
    # The API key (client ID) copied from the Adobe Analytics API client integration.
    @display {label: "", kind: "password"}
    string xApiKey;
|};

public type AnalyticsSegment record {
    Owner owner?;
    string created?;
    # A name for the report suite.  This is deprecated and should use the report suite name instead
    string siteTitle?;
    # A description of the segment
    string description?;
    # The report suite id
    string rsid?;
    # All existing tags associated with the segment
    Tag[] tags?;
    # The friendly name for the report suite id
    string reportSuiteName?;
    # A name for the segment
    string name?;
    string modified?;
    AnalyticsSegmentDefinition definition?;
    string[] categories?;
    SegmentCompatibility compatibility?;
    string definitionLastModified?;
};

public type AnalyticsSegmentDefinitionContainerPred record {
    AnalyticsSegmentDefinitionContainerPredVal val?;
    string str?;
    string func?;
};

# Represents the Queries record for the operation: getCalculatedMetricFunction
public type GetCalculatedMetricFunctionQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: listAnnotations
public type ListAnnotationsQueries record {
    # Sort direction (ASC or DESC
    int sortDirection?;
    # Include additional annotations not owned by user. The "all" option takes precedence over "shared"
    ("all"|"shared")[] includeType?;
    string filterByIds?;
    # Filter list to only include annotations modified since this date (ISO8601 format)
    string filterByModifiedAfter?;
    # Property to sort by (name, modified_date, id is currently allowed)
    string sortProperty = "id";
    # Number of results per page
    int 'limit = 10;
    # Filter list to only include annotations in the specified date range with format yyyy-MM-dd'T'HH:mm:ss/yyyy-MM-dd'T'hh:MM:ss
    string filterByDateRange?;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional annotation metadata fields to include on response
    ("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[] expansion?;
};

# Represents the Queries record for the operation: updateDateRange
public type UpdateDateRangeQueries record {
    # Locale
    string locale = "en_US";
    # Use the new JSON def
    boolean newDefinition = false;
    # Comma-delimited list of additional date range metadata fields to include on response
    ("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[] expansion?;
};

# Represents the Queries record for the operation: createCalculatedMetric
public type CreateCalculatedMetricQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional calculated metric metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[] expansion?;
};

public type CalcMetricFunctionParameter record {
    @jsondata:Name {value: "default-value"}
    record {} defaultValue?;
    string func?;
    string descKey?;
    string name?;
    string friendlyNameKey?;
    string description?;
    string 'type?;
    string friendlyName?;
};

public type ReportMetricPredictiveSettings record {
    decimal anomalyConfidence?;
};

public type SharedToEntity record {
    int:Signed32 shareToId?;
    string shareToType?;
    string accessLevel?;
    string shareToImsId?;
};

# Represents the Queries record for the operation: updateAnnotation
public type UpdateAnnotationQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional annotation metadata fields to include on response
    ("name"|"description"|"dateRange"|"color"|"applyToAllReports"|"scope"|"createdDate"|"modifiedDate"|"modifiedById"|"owner"|"companyId"|"rsid"|"approved"|"favorite"|"shares"|"sharesFullName"|"tags"|"usageSummary"|"usageSummaryWithRelevancyScore"|"ownerFullName"|"reportSuiteName")[] expansion?;
};

public type ReportMetrics record {
    ReportMetric[] metrics?;
    ReportFilter[] metricFilters?;
};

public type SegmentCompatibility record {
    boolean valid?;
    @jsondata:Name {value: "validator_version"}
    string validatorVersion?;
    @jsondata:Name {value: "supported_schema"}
    string[] supportedSchema?;
    @jsondata:Name {value: "supported_features"}
    string[] supportedFeatures?;
    string message?;
    @jsondata:Name {value: "supported_products"}
    string[] supportedProducts?;
};

public type AnalyticsProject record {
    boolean template?;
    Owner owner?;
    record {} complexity?;
    record {|string[]...;|} externalReferences?;
    string accessLevel?;
    string[] migratedIds?;
    string created?;
    string siteTitle?;
    string description?;
    # The report suite id for which the component was created/updated
    string rsid?;
    "project"|"mobileScorecard" 'type?;
    record {|record {}...;|}[] tags?;
    record {|record {}...;|}[] shares?;
    boolean approved?;
    # The report suite name for which the component was created/updated
    string reportSuiteName?;
    string name?;
    string modified?;
    JsonNode definition?;
    record {|record {}...;|} usageSummary?;
    # System generated id
    string id?;
    string versionNotes?;
    boolean companyTemplate?;
    boolean favorite?;
};

public type AnalyticsAnnotation record {
    Owner owner?;
    "STANDARD1"|"STANDARD2"|"STANDARD3"|"STANDARD4"|"STANDARD5"|"STANDARD6"|"STANDARD7"|"STANDARD8"|"STANDARD9" color?;
    string dateRange?;
    boolean systemUserOwned?;
    string description?;
    string rsid?;
    record {|record {}...;|}[] tags?;
    record {|record {}...;|}[] shares?;
    boolean approved?;
    int:Signed32 companyId?;
    string createdDate?;
    string reportSuiteName?;
    string modifiedById?;
    AnnotationScope scope?;
    string name?;
    string modifiedDate?;
    record {|record {}...;|} usageSummary?;
    string id?;
    boolean favorite?;
    boolean applyToAllReports?;
};

# A page of annotations
public type ResponsePageAnalyticsAnnotation record {
    int:Signed32 number?;
    boolean lastPage?;
    int numberOfElements?;
    boolean firstPage?;
    int:Signed32 size?;
    int:Signed32 totalPages?;
    string sort?;
    AnalyticsAnnotation[] content?;
    int totalElements?;
};

# Represents the Queries record for the operation: deleteDateRange
public type DeleteDateRangeQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: getAllSegments
public type GetAllSegmentsQueries record {
    # Sort direction (ASC or DESC
    string sortDirection = "ASC";
    # Include additional segments not owned by user. The "all" option takes precedence over "shared"
    ("shared"|"all"|"templates")[] includeType?;
    # Property to sort by (name, modified_date, id is currently allowed)
    string sortProperty = "id";
    # Filter list to only include segments in the specified list (comma-delimited list of IDs)
    string segmentFilter?;
    # Filter list to only include segments that contains the Name
    string name?;
    # Number of results per page
    int 'limit = 10;
    # Filter list to only include segments tied to specified RSID list (comma-delimited)
    string rsids?;
    # Filter list to only include segments where the published field is set to one of the allowable values (all, true, false)
    "all"|"true"|"false" filterByPublishedSegments = "all";
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Locale
    string locale = "en_US";
    # Filter list to only include segments that contains one of the tags
    string tagNames?;
    # Comma-delimited list of additional segment metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[] expansion?;
};

# Tag Model
public type Tag record {
    # the list of components that have been tagged with this tag
    TaggedComponent[] components?;
    # the tag name 
    string name?;
    # the tag description
    string description?;
    # the tag id
    int:Signed32 id?;
};

public type AlternateVariableNames record {
    string curatedName?;
    string name?;
    string baseName?;
};

public type Share record {
    int:Signed32 shareToId?;
    string componentType?;
    string shareToType?;
    string componentId?;
    string shareToDisplayName?;
    string shareFromImsId?;
    string accessLevel?;
    string shareToImsId?;
    string shareId?;
    string shareToLogin?;
    string imsOrgId?;
};

# Represents the Queries record for the operation: listAllUsersForCompany
public type ListAllUsersForCompanyQueries record {
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
};

public type Locale record {
    string[] unicodeLocaleKeys?;
    string country?;
    string iso3Language?;
    string displayName?;
    string language?;
    string displayVariant?;
    string iso3Country?;
    string displayLanguage?;
    string script?;
    string[] unicodeLocaleAttributes?;
    string displayCountry?;
    string variant?;
    string[] extensionKeys?;
    string displayScript?;
};

public type RankedSummaryData record {
};

public type RankedSettings record {
    boolean includeAnomalyDetection?;
    boolean countRepeatInstances?;
    string dimensionSort?;
    string nonesBehavior?;
    boolean includeForecasting?;
    int:Signed32 'limit?;
    int:Signed32 page?;
    boolean reflectRequest?;
    boolean includePercentChange?;
    boolean includeLatLong?;
};

# Represents the Queries record for the operation: validateProjectDefinition
public type ValidateProjectDefinitionQueries record {
    # Locale
    string locale = "en_US";
};

public type ReportRow record {
    string[] filters?;
    string rowId?;
};

# Represents the Queries record for the operation: saveShareMyCompany
public type SaveShareMyCompanyQueries record {
    # Locale
    string locale = "en_US";
};

public type AnalyticsSegmentDefinitionContainerPredVal record {
    string func?;
    string name?;
    string description?;
};

# Represents the Queries record for the operation: getMetricForReportSuite
public type GetMetricForReportSuiteQueries record {
    # ID of desired report suite
    string rsid;
    # Locale that system named metrics should be returned in
    string locale = "en_US";
    # Add extra metadata to items (comma-delimited list)
    ("tags"|"allowedForReporting"|"categories")[] expansion?;
};

public type ReportMetric record {
    string columnId?;
    ReportMetricPredictiveSettings predictive?;
    string id?;
    string[] filters?;
    string sort?;
    record {|record {}...;|} metricDefinition?;
};

# Represents the Queries record for the operation: updateSegment
public type UpdateSegmentQueries record {
    # Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    string locale = "en_US";
    # Comma-delimited list of additional segment metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[] expansion?;
};

public type UsageLogDto record {
    string dateCreated?;
    string eventDescription?;
    string ipAddress?;
    string rsid?;
    string eventType?;
    string login?;
};

# Represents the Queries record for the operation: getCalculatedMetricFunctions
public type GetCalculatedMetricFunctionsQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: updateProjectConfiguration
public type UpdateProjectConfigurationQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional project metadata fields to include on response
    ("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[] expansion?;
};

public type SavedSharedComponent record {
    Share[] shares?;
    string componentType?;
    string componentId?;
};

public type RankedRequest record {
    RankedSettings settings?;
    ReportSearch search?;
    string rsid?;
    ReportRows rowContainer?;
    string anchorDate?;
    Locale locale?;
    string dimension?;
    ReportFilter[] globalFilters?;
    RankedStatistics statistics?;
    ReportMetrics metricContainer?;
};

public type RankedColumnError record {
    string errorDescription?;
    string columnId?;
    "unauthorized_metric"|"unauthorized_dimension"|"unauthorized_dimension_global"|"anomaly_detection_failure_unexpected_item_count"|"anomaly_detection_failure_tsa_service"|"not_enabled_metric"|"not_enabled_dimension"|"not_enabled_dimension_global" errorCode?;
    string errorId?;
};

public type ComponentSearch record {
    string componentType?;
    string[] componentIds?;
};

public type ReportRows record {
    ReportFilter[] rowFilters?;
    ReportRow[] rows?;
};

# Represents the Queries record for the operation: getProjectConfiguration
public type GetProjectConfigurationQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional project metadata fields to include on response
    ("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[] expansion?;
};

# Represents the Queries record for the operation: createProject
public type CreateProjectQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional project metadata fields to include on response
    ("reportSuiteName"|"shares"|"tags"|"accessLevel"|"modified"|"externalReferences"|"definition")[] expansion?;
};

# Represents the Queries record for the operation: validateSegment
public type ValidateSegmentQueries record {
    # RSID to run the report against
    string rsid;
};

public type ProjectCompatibility record {
    boolean valid?;
    string validatorVersion?;
    string message?;
};

public type NoneSettings record {
    boolean includeNoneByDefault?;
    boolean noneChangeable?;
};

# Represents the Queries record for the operation: getUsageAccessLogs
public type GetUsageAccessLogsQueries record {
    # End date for the maximum of a 3 month period
    string endDate = "2021-01-02T14:32:33-07";
    # The IP address you want to filter logs by
    string ip?;
    # Number of results per page
    int:Signed32 'limit = 10;
    # The report suite ID you want to filter logs by
    string rsid?;
    # The numeric id for the event type you want to filter logs by
    string eventType?;
    # Page number (base 0 - first page is "0")
    int:Signed32 page = 0;
    # The login value of the user you want to filter logs by
    string login?;
    # The event description you want to filter logs by. No wildcards permitted
    string event?;
    # Start date for the maximum of a 3 month period
    string startDate = "2021-01-01T00:00:00-07";
};

public type UnhashReportData record {
    boolean lastPage?;
    string reportId?;
    string searchPhrase?;
    string message?;
    RowItem[] rows?;
    string oberonRequestXML?;
    int:Signed32 totalElements?;
    int:Signed32 number?;
    string searchAnd?;
    boolean firstPage?;
    int:Signed32 numberOfElements?;
    string searchNot?;
    string oberonResponseXML?;
    int:Signed32 totalPages?;
    string searchOr?;
};

public type DeleteResponse record {
    string result?;
    string message?;
};

public type ScopeMetric record {
    string componentType?;
    string id?;
};

public type Row record {
    boolean[] dataAnomalyDetected?;
    decimal[] percentChange?;
    decimal[] dataForecastedLowerBound?;
    decimal[] data?;
    decimal latitude?;
    decimal[] dataForecasted?;
    string rowId?;
    decimal[] dataLowerBound?;
    string itemId?;
    decimal[] dataForecastedUpperBound?;
    decimal[] dataExpected?;
    string value?;
    decimal[] dataUpperBound?;
    decimal longitude?;
};

# Represents the Queries record for the operation: runTopItemReport
public type RunTopItemReportQueries record {
    # Format: YYYY-MM-DD/YYYY-MM-DD
    string dateRange?;
    # Format: YYYY-MM-DD
    string endDate?;
    # A full search phrase that will be searched for
    string searchPhrase?;
    # ID of desired report suite ie. myrsid
    string rsid;
    # Locale that system named metrics should be returned in
    string locale = "en_US";
    # General search string; wrap with single quotes. Example: 'PageABC'
    @http:Query {name: "search-clause"}
    string searchClause?;
    # Search terms that will be AND-ed together. Space delimited
    string searchAnd?;
    # Controls None values to be included
    boolean lookupNoneValues = true;
    # Search terms that will be treated as NOT including. Space delimited
    string searchNot?;
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Search terms that will be OR-ed together. Space delimited
    string searchOr?;
    # Dimension to run the report against. Example: 'variables/page'
    string dimension;
    # Format: YYYY-MM-DD
    string startDate?;
};

# Represents the Queries record for the operation: getSegment
public type GetSegmentQueries record {
    # Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    string locale = "en_US";
    # Comma-delimited list of additional segment metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"compatibility"|"definition"|"publishingStatus"|"definitionLastModified"|"categories")[] expansion?;
};

# Represents the Queries record for the operation: validateCalculatedMetric
public type ValidateCalculatedMetricQueries record {
    # Locale
    string locale = "en_US";
    # Include migration functions in validation
    boolean migrating = false;
};

# Represents the Queries record for the operation: findAllTagsForCompany
public type FindAllTagsForCompanyQueries record {
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
};

# Represents the Queries record for the operation: deleteSegment
public type DeleteSegmentQueries record {
    # Locale. Valid values include 'en_US', 'fr_FR', 'ja_JP', 'de_DE', 'es_ES', 'ko_KR', 'pt_BR', 'zh_CN', and 'zh_TW'
    string locale = "en_US";
};

# Represents the Queries record for the operation: findAllSharesForCompany
public type FindAllSharesForCompanyQueries record {
    # Include additional shares not owned by the user
    ("sharedTo")[] includeType?;
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # The user ID to return details for. Only admins may use this option
    int:Signed32 userid?;
};

# Represents the Queries record for the operation: deleteAnnotation
public type DeleteAnnotationQueries record {
    # Locale
    string locale = "en_US";
};

# Represents the Queries record for the operation: updateCalculatedMetric
public type UpdateCalculatedMetricQueries record {
    # Locale
    string locale = "en_US";
    # Comma-delimited list of additional calculated metric metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[] expansion?;
};

public type AnalyticsSegmentDefinitionContainer record {
    string func?;
    AnalyticsSegmentDefinitionContainerPred pred?;
    string context?;
};

# Represents the Queries record for the operation: getTagListByComponentIdAndComponentType
public type GetTagListByComponentIdAndComponentTypeQueries record {
    # The component type to operate on
    "segment"|"dashboard"|"bookmark"|"calculatedMetric"|"project"|"dateRange"|"metric"|"dimension"|"virtualReportSuite"|"scheduledJob"|"alert"|"classificationSet" componentType;
    # The componentId to operate on. Currently this is just the segmentId
    string componentId;
};

# A page of date ranges
public type ResponsePageExpandedDateRange record {
    int:Signed32 number?;
    boolean lastPage?;
    int numberOfElements?;
    boolean firstPage?;
    int:Signed32 size?;
    int:Signed32 totalPages?;
    string sort?;
    ExpandedDateRange[] content?;
    int totalElements?;
};

public type RankedColumnMetaData record {
    string[] columnIds?;
    RankedColumnError[] columnErrors?;
    ReportDimension dimension?;
};

public type CalculatedMetricDef record {
};

# Represents the Queries record for the operation: searchComponentTags
public type SearchComponentTagsQueries record {
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
};

public type RankedStatistics record {
    string[] functions?;
    boolean ignoreZeroes?;
};

# Represents the Queries record for the operation: getDimensionForReportSuite
public type GetDimensionForReportSuiteQueries record {
    # The report suite ID
    string rsid;
    # The locale to use for returning system named dimensions
    string locale = "en_US";
    # Add extra metadata to items (comma-delimited list)
    ("tags"|"allowedForReporting"|"attributionModel"|"categories"|"allocationType"|"expirationType"|"expirationCustomDays"|"dataType"|"bindingEvents"|"merchandisingSyntax")[] expansion?;
};

# Represents the Queries record for the operation: deleteTagItemsFromComponents
public type DeleteTagItemsFromComponentsQueries record {
    # The component type to operate on
    "segment"|"dashboard"|"bookmark"|"calculatedMetric"|"project"|"dateRange"|"metric"|"dimension"|"virtualReportSuite"|"scheduledJob"|"alert"|"classificationSet" componentType;
    # Comma-separated list of componentIds to operate on
    string componentIds;
};

public type TaggedComponent record {
    string componentType?;
    string componentId?;
    string[] tags?;
};

public type AnalyticsCalculatedMetric record {
    Owner owner?;
    # Calculated metric creation date
    string created?;
    # Number of decimal places to include in calculated metric result
    int:Signed32 precision?;
    string siteTitle?;
    string description?;
    # The report suite id for which the component was created/updated
    string rsid?;
    "CURRENCY"|"TIME"|"DECIMAL"|"PERCENT" 'type?;
    Tag[] tags?;
    # The report suite name for which the component was created/updated
    string reportSuiteName?;
    string name?;
    string modified?;
    CalculatedMetricDef definition;
    # System generated id
    string id?;
    string[] categories?;
    # Set metric polarity, which indicates whether it's good or bad if a given metric goes up. Default=positive
    "positive"|"negative" polarity?;
};

# Represents the Queries record for the operation: getDateRangesForUser
public type GetDateRangesForUserQueries record {
    # Include additional dateranges not owned by user. The "all" option takes precedence over "shared"
    ("all"|"shared"|"templates"|"curatedItem")[] includeType?;
    # Filter list to only include date ranges in the specified list (comma-delimited list of IDs)
    string filterByIds?;
    # Filter list to only include date ranges modified since this date (ISO8601 format)
    string filterByModifiedAfter?;
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Locale
    string locale = "en_US";
    # Use the new JSON def
    boolean newDefinition = false;
    # Comma-delimited list of additional date range metadata fields to include on response
    ("definition"|"ownerFullName"|"modified"|"approved"|"favorite"|"shares"|"tags"|"sharesFullName"|"usageSummary"|"usageSummaryWithRelevancyScore")[] expansion?;
    # Include the curatedItem status for given Rsid
    string curatedRsid?;
};

public type ReportSearch record {
    string clause?;
    boolean includeSearchTotal?;
    string[] itemIds?;
    string[] excludeItemIds?;
    boolean empty?;
};

# Represents the Queries record for the operation: findCalculatedMetrics
public type FindCalculatedMetricsQueries record {
    # Include additional calculated metrics not owned by user. The "all" option takes precedence over "shared"
    ("all"|"shared"|"templates")[] includeType?;
    # Property to sort by (name, modified_date, id is currently allowed)
    string sortProperty = "id";
    # Filter list to only include calculated metrics tied to specified RSID list (comma-delimited)
    string rsids?;
    # Filter list to only include calculated metrics owned by the specified loginId
    int:Signed32 ownerId?;
    # Locale
    string locale = "en_US";
    # Filter list to only include calculated metrics that contains one of the tags
    string tagNames?;
    # Comma-delimited list of additional calculated metric metadata fields to include on response
    ("reportSuiteName"|"ownerFullName"|"modified"|"tags"|"definition"|"compatibility"|"categories")[] expansion?;
    # Filter list to only include calculated metrics that are approved
    boolean approved?;
    # Sort direction (ASC or DESC)
    string sortDirection = "ASC";
    # Filter list to only include calculated metrics in the specified list (comma-delimited list of IDs) (this is the same as calculatedMetricFilter, and is overwritten by calculatedMetricFilter
    string filterByIds?;
    # Filter list to only include calculated metrics that contains the Name
    string name?;
    # Number of results per page
    int 'limit = 10;
    # Page number (base 0 - first page is "0")
    int page = 0;
    # Filter list to only include calculated metrics that are favorites
    boolean favorite?;
    # The report suite where the calculated metric intended to be used.  This report suite will be used to determine things like compatibility and permissions.  If it is not specified then the permissions will be calculated based on the union of all metrics authorized in all groups the user belongs to.  If the compatibility expansion is specified and toBeUsedInRsid is not then the compatibility returned is based off the compatibility from the last time the calculated metric was saved
    string toBeUsedInRsid?;
};

public type ExpandedDateRange record {
    record {} owner?;
    boolean template?;
    boolean systemUserOwned?;
    string disabledDate?;
    string description?;
    record {|record {}...;|}[] tags?;
    record {|record {}...;|}[] shares?;
    int:Signed32 companyId?;
    boolean approved?;
    AlternateVariableNames alternateVariableNames?;
    string name?;
    boolean curatedItem?;
    string modified?;
    record {} definition?;
    record {|record {}...;|} usageSummary?;
    string id?;
    boolean favorite?;
    string imsOrgId?;
    string createDate?;
};
